# Generated by Django 3.1.7 on 2021-03-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='main_app.Profile'),
        ),
    ]
