# Generated by Django 3.1.7 on 2021-03-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
            preserve_default=False,
        ),
    ]
