# Generated by Django 3.1.7 on 2021-03-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210318_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='city',
            name='photographer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
